#carddataclass.py
""""Card data class with class attributes, data attributes, autogenerated methods and explicitly defined methods"""
from dataclasses import dataclass
from typing import ClassVar, List

@dataclass              #(order = True) autogenerate overloaded comparison operator methods     This will be a data class
class Card:
    FACES: ClassVar[List[str]] = ['Ace', '2', '3', '4', '5', '6', '7', '8', '9', '10','Jack', 'Queen', 'King']      #Class attributes which refers to a list of strings
    SUITS: ClassVar[List[str]] = ['Hearts', 'Diamonds', 'Clubs', 'Spades']

    face: str               #Data attribute that indicate face refers to string object
    suit: str
    #A dataclass may contain properties and methods and participate in class hierarchies
    @property
    def image_name(self):               #Create image_name property dynamically
        """Return the Card's image file name"""
        return str(self).replace(' ','_') + '.png'          #Getting the Card object's string representation with underscores and filename extension

    def __str__(self):
        """Return a string representation of the card"""
        return f'{self.face} of {self.suit}'

    def __format__(self, format):
        """Return formatted string representation of the card"""
        return f'{str(self):{format}}'          #



